UPOD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Accounts
    path('accounts/', include('allauth.urls')),
    # Local Paths
    path('', include('upodusers.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('reservations/', include('reservations.urls')),
    path('events/', include('events.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'UPOD.views.handler404'
handler500 = 'UPOD.views.handler500'
handler403 = 'UPOD.views.handler403'
handler400 = 'UPOD.views.handler400'

dashboard/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'dashboard'

urlpatterns = [
    # path('', views.index, name='index'),
    path('accounts/logout/', LogoutView.as_view(), name="account_logout"),
    path('', views.render_dashboard, name='dashboardhome'),
    path('logout/user/', views.logout_views, name='logout_views'),
    path('about/', views.about_us, name='about_us'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.render_events, name='events'),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    # URL pattern for the room app
    path('selection/', views.show_selection, name='room_selection'),
]

rooms/models.py
from django.db import models

class Room(models.Model):
    roomlabel = models.CharField(max_length=100, unique=True)
    capacity = models.PositiveIntegerField()

    def __str__(self):
        return self.roomlabel


class Calendar(models.Model):
    room = models.OneToOneField(Room, on_delete=models.CASCADE, related_name="calendar")

    def __str__(self):
        return f"{self.room.roomlabel}'s Calendar"


class DateEntry(models.Model):
    calendar = models.ForeignKey(Calendar, on_delete=models.CASCADE, related_name="date_entries")
    date = models.DateField()

    class Meta:
        unique_together = ('calendar', 'date')

    def __str__(self):
        return f"{self.calendar.room.roomlabel} - {self.date}"


class TimeReserved(models.Model):
    date_entry = models.ForeignKey(DateEntry, on_delete=models.CASCADE, related_name="time_reservations")
    starting_time = models.TimeField()
    ending_time = models.TimeField()
    event = models.OneToOneField('events.Event', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.date_entry} [{self.starting_time} - {self.ending_time}]"

rooms/views.py
from django.shortcuts import render, redirect
from .models import Room
from django.conf import settings

# Create your views here.
def show_selection(request):
    if request.user.is_authenticated:
        rooms = Room.objects.all()

        return render(request, 'rooms/roomselection.html', {'rooms': rooms})
    return redirect(settings.ACCOUNT_LOGOUT_REDIRECT_URL)

rooms/templates/rooms/roomselection.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'rooms/css/room.css' %}?v=4">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@2.0.4" 
    integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" 
    crossorigin="anonymous"></script>
</head>
<body>
    <nav>
        <div class="nav-logo"><a href="landing.html">UPOD</a></div>
        <ul class="nav-links">
        <li class="landing"><a href="{% url 'dashboard:dashboardhome' %}">Home</a></li>
        <li class="registration"><a href="{% url 'rooms:room_selection' %}">Registration</a></li>
        <li class="events"><a href="{% url 'events:events' %}">Events</a></li>
        <li class="my_qr"><a href="{% url 'dashboard:about_us' %}">About Us</a></li>

            <div class="profile-dropdown">
                <a href="../templates/profile.html" title="My Profile">
                    <i class="fa-regular fa-circle-user"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'dashboard:profile' %}">View Profile</a></li>
                    <form method="POST" no_visible_fields=True >
                        {% csrf_token %}
                        <li class="logout">
                            <a  hx-post="{% url 'dashboard:logout_views' %}?next=/" 
                                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                            hx-target="body" 
                            hx-swap="none" 
                            hx-confirm="Are you sure you want to log out?">Logout</a>
                    </li>
                    </form>
                </ul>
            </div>
        </ul>
    </nav>

    <div class="container">
        <header>
                <h1>ILC Rooms</h1>
        </header>

        <main class="rooms-container">
            {% for room in rooms %}
                <div class="room-card">
                    <div class="room-image" style="background-color: #5c48ee">
                        <span class="room-number">{{ room.roomlabel }}</span>
                    </div>
                    <div class="room-details">
                        <h2>{{ room.roomlabel }}</h2>
                        <p>Capacity: {{ room.capacity }}</p>
                        <a href="{% url 'create_reservation' room.id %}">
                        <button class="register-btn" type="button">Reserve Room</button>
                    </a>    
                    </div>    
                </div>
            {% endfor %}
        </main>
    </div>
        

    {% comment %} {% for room in rooms %}
    <div class="room-card">
        <h3>{{ room.roomlabel }}</h3>
        <p>Capacity: {{ roomggd.capacity }}</p>
        <a href="{% url 'create_reservation' room.id %}">
            <button type="button">Reserve {{ room.roomlabel }}</button>
        </a>        
    </div>
    {% endfor %} {% endcomment %}

    {% comment %} <main class="rooms-container">
            <div class="room-card">
                <div class="room-image" style="background-color: #5c48ee;">
                    <span class="room-number">Room 101</span>
                </div>
                <div class="room-details">
                    <h2>Conference Room A</h2>
                    <p>Capacity: 20 people</p>
                    <p>Features: Projector, Whiteboard, Video Conferencing</p>
                    <button class="register-btn" onclick="window.location.href='user_status_r1.html'">Register Event</button>
                </div>
            </div> {% endcomment %}
</body>
</html>